/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardForensicRouteImport } from './routes/dashboard.forensic'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard.compliance'
import { Route as DashboardCoachingRouteImport } from './routes/dashboard.coaching'
import { Route as DashboardBranchDebugRouteImport } from './routes/dashboard.branch-debug'
import { Route as ApiPublicBranchDebugRouteImport } from './routes/api/public/branch-debug'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForensicRoute = DashboardForensicRouteImport.update({
  id: '/forensic',
  path: '/forensic',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoachingRoute = DashboardCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchDebugRoute = DashboardBranchDebugRouteImport.update({
  id: '/branch-debug',
  path: '/branch-debug',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicBranchDebugRoute = ApiPublicBranchDebugRouteImport.update({
  id: '/api/public/branch-debug',
  path: '/api/public/branch-debug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/branch-debug': typeof DashboardBranchDebugRoute
  '/dashboard/coaching': typeof DashboardCoachingRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/forensic': typeof DashboardForensicRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/branch-debug': typeof ApiPublicBranchDebugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/branch-debug': typeof DashboardBranchDebugRoute
  '/dashboard/coaching': typeof DashboardCoachingRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/forensic': typeof DashboardForensicRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/branch-debug': typeof ApiPublicBranchDebugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/branch-debug': typeof DashboardBranchDebugRoute
  '/dashboard/coaching': typeof DashboardCoachingRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/forensic': typeof DashboardForensicRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/branch-debug': typeof ApiPublicBranchDebugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/branch-debug'
    | '/dashboard/coaching'
    | '/dashboard/compliance'
    | '/dashboard/forensic'
    | '/dashboard/reports'
    | '/dashboard/'
    | '/api/public/branch-debug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/branch-debug'
    | '/dashboard/coaching'
    | '/dashboard/compliance'
    | '/dashboard/forensic'
    | '/dashboard/reports'
    | '/dashboard'
    | '/api/public/branch-debug'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/branch-debug'
    | '/dashboard/coaching'
    | '/dashboard/compliance'
    | '/dashboard/forensic'
    | '/dashboard/reports'
    | '/dashboard/'
    | '/api/public/branch-debug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiPublicBranchDebugRoute: typeof ApiPublicBranchDebugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/forensic': {
      id: '/dashboard/forensic'
      path: '/forensic'
      fullPath: '/dashboard/forensic'
      preLoaderRoute: typeof DashboardForensicRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/coaching': {
      id: '/dashboard/coaching'
      path: '/coaching'
      fullPath: '/dashboard/coaching'
      preLoaderRoute: typeof DashboardCoachingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branch-debug': {
      id: '/dashboard/branch-debug'
      path: '/branch-debug'
      fullPath: '/dashboard/branch-debug'
      preLoaderRoute: typeof DashboardBranchDebugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/branch-debug': {
      id: '/api/public/branch-debug'
      path: '/api/public/branch-debug'
      fullPath: '/api/public/branch-debug'
      preLoaderRoute: typeof ApiPublicBranchDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBranchDebugRoute: typeof DashboardBranchDebugRoute
  DashboardCoachingRoute: typeof DashboardCoachingRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardForensicRoute: typeof DashboardForensicRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBranchDebugRoute: DashboardBranchDebugRoute,
  DashboardCoachingRoute: DashboardCoachingRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardForensicRoute: DashboardForensicRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiPublicBranchDebugRoute: ApiPublicBranchDebugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
